### ISSUE TITLE
Feature Request: Add dependencies to install

### ISSUE THREAD

**Issue by JayWll** [JurajNyiri/pytapo#122]
It seems something changed on July 5th or 6th and I now get an error when attempting to use the library:

```
Traceback (most recent call last):
  File "/exec.py", line 7, in <module>
    from pytapo.media_stream.downloader import Downloader
  File "/usr/local/lib/python3.12/site-packages/pytapo/media_stream/downloader.py", line 1, in <module>
    from .convert import Convert
  File "/usr/local/lib/python3.12/site-packages/pytapo/media_stream/convert.py", line 7, in <module>
    import aiofiles
ModuleNotFoundError: No module named 'aiofiles'
```

I know very little about python, but I believe this indicates a new, unmet, dependency on another library. I solved for it by doing a `pip install aiofiles` as a workaround and things are working once again, but is there perhaps somewhere where dependencies are defined that's missing this one?

**Comment by JurajNyiri** [comment]
Yes this dependency was added recently, I renamed this as a feature request to add dependencies to this project.

**Comment by nop64-sudo** [comment]
Hello,

I installed a fresh version on a new platform.
I had an error with module kasa not found.
I then installed using  pip3 install python-kasa and now i have an other depency issue.

File "/usr/local/lib/python3.9/dist-packages/pytapo/__init__.py", line 12, in <module>
    from kasa.transports import KlapTransportV2, KlapTransport
ModuleNotFoundError: No module named 'kasa.transports'

I had no issue with an old  version ( 3.3.36)
Do you have a list of dependencies and versions of python modules to install with this newest version ? 
Many thanks

Regards,

**Comment by JurajNyiri** [comment]
Use python3.13.
