### ISSUE TITLE
SSL Error with Tapo C110

### ISSUE THREAD

**Issue by meju25** [JurajNyiri/pytapo#131]
Hello,

I was using pytapo for some time without any issue, till the issue https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551 popped up. 
As there is a fix for that available now, I tried again and I get an SSL error now. (Trace below).

Anybody an idea what I am doing wrong?

Thanks and br, Jürgen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\git\pytapo\experiments\DownloadRecordings.py", line 29, in
tapo = Tapo(host, user, password_cloud, password_cloud)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\juerg\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytapo_init_.py", line 86, in init
self.basicInfo = self.getBasicInfo()
^^^^^^^^^^^^^^^^^^^
File "C:\Users\juerg\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytapo_init_.py", line 1009, in getBasicInfo
return self.executeFunction(
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\juerg\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytapo_init_.py", line 491, in executeFunction
data = self.performRequest(
^^^^^^^^^^^^^^^^^^^^
File "C:\Users\juerg\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytapo_init_.py", line 530, in performRequest
self.ensureAuthenticated()
File "C:\Users\juerg\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytapo_init_.py", line 108, in ensureAuthenticated
return self.refreshStok()
^^^^^^^^^^^^^^^^^^
File "C:\Users\juerg\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytapo_init_.py", line 305, in refreshStok
if self.isSecureConnection():
^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\juerg\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytapo_init_.py", line 212, in isSecureConnection
res = self.request(
^^^^^^^^^^^^^
File "C:\Users\juerg\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytapo_init_.py", line 163, in request
response = session.request(method, url, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\juerg\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\juerg\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\juerg\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 517, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.0.100', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)')))

D:\git\pytapo\experiments>

**Comment by meju25** [comment]
This has been resolved. I updated to python 3.13.1, installed pytapo again and now it works without any issue.

Thanks for your great work @JurajNyiri !
