### ISSUE TITLE
connect externally

### ISSUE THREAD

**Issue by ruirigel** [JurajNyiri/pytapo#27]
is it possible to use pytapo to connect to tapo externally? I have received errors when trying to do this.

**Comment by JurajNyiri** [comment]
Your camera has to be available on specified IP and ports. If it is (IP is public and ports are forwarded), it can be accessed remotely.

**Comment by ruirigel** [comment]
I have access to tapo externally on port 553, from here I get video. I placing the wrong port to control the camera via pytapo?

`#!/usr/bin/env python3

from pytapo import Tapo

user = "username" # user you set in Advanced Settings -> Camera Account
password = "password" # password you set in Advanced Settings -> Camera Account
host = "address:551" # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password)



print(tapo.getBasicInfo())

`

`x@x-K52Jr:~$ python3 tapo.py 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aosr.no-ip.org', port=551): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tapo.py", line 9, in <module>
    tapo = Tapo(host, user, password)
  File "/home/x/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 40, in __init__
    self.basicInfo = self.getBasicInfo()
  File "/home/x/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 232, in getBasicInfo
    return self.performRequest(
  File "/home/x/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 94, in performRequest
    self.ensureAuthenticated()
  File "/home/x/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 60, in ensureAuthenticated
    return self.refreshStok()
  File "/home/x/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 73, in refreshStok
    res = requests.post(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='aosr.no-ip.org', port=551): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
`
