### ISSUE TITLE
C310

### ISSUE THREAD

**Issue by ruirigel** [JurajNyiri/pytapo#28]
any way to use pytapo on c310?

**Comment by JurajNyiri** [comment]
Yes, use "admin" username and your cloud password.

**Comment by ruirigel** [comment]
the tapo app in advanced account settings, not allow to put the username admin
any advice?

```
python3 tapo.py 
Traceback (most recent call last):
  File "tapo.py", line 9, in <module>
    tapo = Tapo(host, user, password)
  File "/home/x/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 40, in __init__
    self.basicInfo = self.getBasicInfo()
  File "/home/x/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 232, in getBasicInfo
    return self.performRequest(
  File "/home/x/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 94, in performRequest
    self.ensureAuthenticated()
  File "/home/x/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 60, in ensureAuthenticated
    return self.refreshStok()
  File "/home/x/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 79, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data
```

**Comment by JurajNyiri** [comment]
You do not need to provide it to the advanced settings. Just use "admin" and your cloud password in pytapo.

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/41
