### ISSUE TITLE
Control camera remotely

### ISSUE THREAD

**Issue by thoithoi58** [JurajNyiri/pytapo#40]
Hi,

I have a Tapo C200 that configured which DDNS and Port Forwarding, so I have no problem streaming in RTSP with VLC. However when I use the domain in host parameter (e.g. mydomain.ddns.net:554), It throw an error:

```
Traceback (most recent call last):
  File "c:\Users\ThoaiNguyen(Intern)\Documents\tapo_controller\testt.py", line 7, in <module>
    tapo = Tapo(host, user, password)
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 41, in __init__
    self.basicInfo = self.getBasicInfo()
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 232, in getBasicInfo
    return self.performRequest(
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 95, in performRequest
    self.ensureAuthenticated()
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 61, in ensureAuthenticated
    return self.refreshStok()
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 74, in refreshStok
    res = requests.post(
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='abcxyz.ddns.net', port=554): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))
```
How can I fix it? Thank you

**Comment by thoithoi58** [comment]
ALso, when I remove the port, it says: `
```
C:\Users\ThoaiNguyen(Intern)\Documents\tapo_controller>"C:/Program Files/Python39/python.exe" c:/Users/ThoaiNguyen(Intern)/Documents/tapo_controller/testt.py
Traceback (most recent call last):
  File "c:\Users\ThoaiNguyen(Intern)\Documents\tapo_controller\testt.py", line 7, in <module>
    tapo = Tapo(host, user, password)
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 41, in __init__
    self.basicInfo = self.getBasicInfo()
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 232, in getBasicInfo      
    return self.performRequest(
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 95, in performRequest     
    self.ensureAuthenticated()
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 61, in ensureAuthenticated
    return self.refreshStok()
  File "C:\Users\ThoaiNguyen(Intern)\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 80, in refreshStok        
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data
```

**Comment by JurajNyiri** [comment]
There is no port 554 on the camera. Remapping of ports is not supported in this integration. 
Port forwarding your camera to the internet is also a really bad idea so this will not be considered as a feature.

**Comment by JurajNyiri** [comment]
Camera control communicates via port 443
554 is only for rtsp. 

Opening your camera to the internet is a terrible idea.
