### ISSUE TITLE
Invalid authentication data after firmware upgrade

### ISSUE THREAD

**Issue by gulinmar** [JurajNyiri/pytapo#85]
I'm using the example script (https://github.com/JurajNyiri/pytapo/blob/main/experiments/DownloadRecordings.py) to download videos from the camera SD card and after upgrade the firmware to the latest version, I've started to receive an error:

Connecting to camera...
Traceback (most recent call last):
  File "/home/zeus/bin/tapo_downloader.py", line 19, in <module>
    tapo = Tapo(host, "admin", password_cloud, password_cloud)
  File "/home/zeus/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 48, in __init__
    self.basicInfo = self.getBasicInfo()
  File "/home/zeus/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 446, in getBasicInfo
    return self.executeFunction(
  File "/home/zeus/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 119, in executeFunction
    data = self.performRequest(
  File "/home/zeus/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 148, in performRequest
    self.ensureAuthenticated()
  File "/home/zeus/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 68, in ensureAuthenticated
    return self.refreshStok()
  File "/home/zeus/.local/lib/python3.8/site-packages/pytapo/__init__.py", line 98, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data

I'm using user "admin" and the cloud password but I've tried with the camera user/password with the same result. 
Any help would be appreciated, thank you!

**Comment by JurajNyiri** [comment]
Make sure to put correct password_cloud in the variable. Camera might not have up-to-date password if you have it blocked in firewall. You can remove the camera, factory reset and add back to account in order for it to get new password if you changed it recently.
