### ISSUE TITLE
How to use? / Dont work with useraccount and "admin"

### ISSUE THREAD

**Issue by solisinvictum** [JurajNyiri/pytapo#87]
Like the Titel says.

Quiet dont understand how to use it.

Installed pytapo, created "device account" on the tapo app (it works, zoneminder use it already over rtsp).

Created a test.py like described:

```
from pytapo import Tapo

user = "admin" # user you set in Advanced Settings -> Camera Account
password = "yopasswordsecret" # password you set in Advanced Settings -> Camera Account
host = "192.168.5.226" # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password)

print(tapo.getBasicInfo())
```

Tried user, the user i set in the app. both dont work:

```
#: python test.py 
Traceback (most recent call last):
  File "/home/user/test.py", line 7, in <module>
    tapo = Tapo(host, user, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 86, in __init__
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 1009, in getBasicInfo
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 491, in executeFunction
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 530, in performRequest
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 108, in ensureAuthenticated
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 418, in refreshStok
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 418, in refreshStok
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 423, in refreshStok
Exception: Invalid authentication data

```

What i try to do, is to be able to move and tilt my camera.

**Comment by JurajNyiri** [comment]
For admin account use your tplink cloud pwd.

**Comment by JurajNyiri** [comment]
Because it works for hundreds others with this exact configuration with no issues and it's support question not an actual issue that needs to be fixed.

**Comment by solisinvictum** [comment]
-Tapoversion: Latest from Google Play available for Google Pixel 7 Pro. Version 3.1.315(1065)
-Tapo C200 Version 1.3.9 Build 231019 Rel.29120n(4555)

What i have done: 

-Exactly what the App wanted. Everything works on the App. Created local account under advanced settings (user: userab, password: the same like for the cloud. both works (can log in the app, and can watch rtsp stream with that password)).
-Intalled pytapo, created test.py with the content like posted.
-executed the script with python test.py (as user and root, linux)

>>[...]as well as enable debug logs and post that.

how do i enable debug logs pytapo?

**Comment by JurajNyiri** [comment]
What pytapo version are you using? 

Set printDebugInformation to true in [initializer](https://github.com/JurajNyiri/pytapo/blob/main/pytapo/__init__.py#L33) of pytapo.

**Comment by solisinvictum** [comment]
>> What pytapo version are you using?

git. so the latest available. 20 Nov. 2023.

>> Set printDebugInformation to true in [initializer](https://github.com/JurajNyiri/pytapo/blob/main/pytapo/__init__.py#L33) of pytapo.

How i do that? I dont have a __init__.py file on my System: 

<img width="751" alt="grafik" src="https://github.com/JurajNyiri/pytapo/assets/94938946/35afc356-8ee7-4924-a071-7469cbe40768">

**Comment by JurajNyiri** [comment]
Pass it to the pytapo initializer inside function Tapo(host, user, password)
