### ISSUE TITLE
How to use? / Dont work with useraccount and "admin"

### ISSUE THREAD

**Issue by solisinvictum** [JurajNyiri/pytapo#88]
Like the Titel says.

Quiet dont understand how to use it.

Installed pytapo, created "device account" on the tapo app (it works, zoneminder use it already over rtsp).

Created a test.py like described:

```
from pytapo import Tapo

user = "admin" # user you set in Advanced Settings -> Camera Account
password = "yopasswordsecret" # password you set in Advanced Settings -> Camera Account
host = "192.168.5.226" # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password)

print(tapo.getBasicInfo())
```

Tried admin, the user i set in the app. both dont work:

```
#: python test.py 
Traceback (most recent call last):
  File "/home/user/test.py", line 7, in <module>
    tapo = Tapo(host, user, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 86, in __init__
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 1009, in getBasicInfo
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 491, in executeFunction
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 530, in performRequest
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 108, in ensureAuthenticated
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 418, in refreshStok
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 418, in refreshStok
  File "/usr/lib/python3.11/site-packages/pytapo-3.3.18-py3.11.egg/pytapo/__init__.py", line 423, in refreshStok
Exception: Invalid authentication data

```

What i try to do, is to be able to move and tilt my camera. 

PS:

Open new Issue, because old got directly closed with the Text: "For admin account use your tplink cloud pwd."

The Password is exactly the same like the "local account on the camera" wich zoneminder uses.

PSS: I edited this post. Of course i tried the user admin. And the User i created in the app. 

I tried to change the user in the app to admin even.

But neitherless what i do, nothing works. (Execpt zoneminder wich works just fine).

**Comment by JurajNyiri** [comment]
Please stop creating new issues. Use the one I already responded to and gave a solution.
