### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by slavino** [JurajNyiri/pytapo#91]
```
Traceback (most recent call last):
  File "/home/pi/workspace/pytapo/camGarageHouse2.py", line 7, in <module>
    tapo = Tapo(host, user, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 86, in __init__
    self.basicInfo = self.getBasicInfo()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 1009, in getBasicInfo
    return self.executeFunction(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 491, in executeFunction
    data = self.performRequest(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 530, in performRequest
    self.ensureAuthenticated()
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 108, in ensureAuthenticated
    return self.refreshStok()
           ^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 418, in refreshStok
    return self.refreshStok(loginRetryCount)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 418, in refreshStok
    return self.refreshStok(loginRetryCount)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 423, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data
```

Just to make sure - If I can watch the RTSP stream with
`rtsp://userName:UserPassWd@192.168.1.33:554/stream1` on both Tapo cameras C320WS (Firmware: 1.1.6) and C310 (Firmware: 1.3.9) with no active TapoCloud subscription, relying just on SD card recordings.

Which password should I use?

Reason for not experimenting too much is this: 

```
Traceback (most recent call last):
  File "/home/pi/workspace/pytapo/camGarageHouse2.py", line 7, in <module>
    tapo = Tapo(host, user, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 86, in __init__
    self.basicInfo = self.getBasicInfo()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 1009, in getBasicInfo
    return self.executeFunction(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 491, in executeFunction
    data = self.performRequest(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 530, in performRequest
    self.ensureAuthenticated()
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 108, in ensureAuthenticated
    return self.refreshStok()
           ^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/pytapo/__init__.py", line 444, in refreshStok
    raise Exception(
Exception: Temporary Suspension: Try again in 1800 seconds
```

**Comment by JurajNyiri** [comment]
Use "admin" username along your password for tplink account.
